create database consumer_behaviour;
use consumer_behaviour;

SELECT * FROM customer;


-- 1 what is the Total revenue generated by male vs female?
SELECT gender, SUM(purchase_amount) revenue
FROM customer GROUP BY gender;
-- 2 which customer used a discount but still spend more than average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- 3 which are the 5 top product with highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) as Average_Product_Rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4 compare the average purchase amounts and standard and express shipping?  
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) avg_price
FROM customer WHERE shipping_type IN ('Standard' , 'Express') GROUP BY shipping_type;

-- 5 Do subscribers customer spends more? compare average spending and total revenue 
-- between subscribers and non-subscribers 
SELECT subscription_status, COUNT(customer_id) Total_customers,ROUND(AVG(purchase_amount), 2) Avg_spend,
SUM(purchase_amount) Total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY Total_revenue , Avg_spend DESC;

-- 6 Which 5 product have the highest percentage of purchases with discounts applied? 
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate 
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC LIMIT 5;

-- 7 segment customers into new ,returning , and loyal based on their 
-- total number of previous purchases and show the count of each segment
SELECT
  CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    WHEN previous_purchases >= 10 THEN 'Loyal'
  END AS customer_segment,
  COUNT(*) AS segment_count
FROM customer
GROUP BY customer_segment;

-- 8 what are the top 3 most purchased products within each category?

with RankedProducts AS (SELECT category, item_purchased, count(customer_id) AS total_orders,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY count(customer_id) DESC) AS item_rank
    FROM customer
  GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders FROM RankedProducts
WHERE item_rank <= 3 ORDER BY category, item_rank;

-- 9 Are customers who are repeat buyers (more than 5 previous purchases) also likly to subscribe?
SELECT COUNT(customer_id) repeat_buyer, subscription_status
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10 what is Total Revenue contributed each age group?
SELECT Age_group, SUM(purchase_amount) total_revenue
FROM customer
GROUP BY Age_group
ORDER BY total_revenue DESC;
